# Generated by Django 3.0.5 on 2020-09-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qolab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
