# Generated by Django 3.0.5 on 2020-09-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qolab', '0002_timer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='emails',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='timer',
            name='names',
            field=models.CharField(default='Name', max_length=20000),
        ),
        migrations.AddField(
            model_name='timer',
            name='youtube',
            field=models.CharField(default='youtube.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='timer',
            name='day',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='timer',
            name='end',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start',
            field=models.CharField(max_length=2000),
        ),
    ]
